version: 2

before:
  hooks:
    - ./scripts/fetch-opencode.sh

builds:
  - id: jul
    dir: apps/cli
    main: ./cmd/jul
    binary: jul
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: jul
    ids:
      - jul
    name_template: "jul_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    files:
      - src: build/opencode/{{ .Os }}_{{ .Arch }}/opencode
        dst: libexec/jul/opencode

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - name: jul
    homepage: https://github.com/lydakis/jul
    description: Jul CLI with bundled OpenCode agent
    ids:
      - jul
    binaries:
      - jul
    repository:
      owner: lydakis
      name: homebrew-jul
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
